version: "3"
services:
  
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    container_name: db

  server:
    build: ./server
    stdin_open: true
    ports:
      - "5000:5000"
    depends_on:
      - db
    container_name: server
