version: "3.7"
services:

  dbserver:
    image: mysql:5.7
    container_name: dbserver
    environment:
      MYSQL_ROOT_PASSWORD: root
    # volumes:
      # - ./db_server/data:/var/lib/mysql/:rw

  server:
    build: ./server
    container_name: server
    ports:
      - "5001:5000"
    depends_on:
      - dbserver

  dbauth:
    image: mysql:5.7
    container_name: dbauth
    environment:
      MYSQL_ROOT_PASSWORD: root
    # volumes:
      # - ./db_auth/data:/var/lib/mysql/:rw
    
  auth:
    build: ./auth
    container_name: auth
    ports:
      - "5000:5000"
    depends_on:
      - dbauth
      - server

# networks:
#   reachable:
#   unreachable:
#     driver: overlay
#     internal: true
